name: Maven Package
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Replace Maven Credentials
        run: |
          sed -i 's/USERNAME/${{ secrets.USERNAME }}/g' .github/settings.xml
          sed -i 's/PASSWORD/${{ secrets.PASSWORD }}/g' .github/settings.xml

      - name: Install
        run: ./mvnw clean install -s .github/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.github.token }}
